### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by mczac** [peteakalad/homebridge-dyson360eye#1]
Awesome module!
Just a small feature request, is it possible to post incremental status updates into the logs, rather than MQTT logs like: {"msg":"CURRENT-STATE","state":"INACTIVE_CHARGING","fullCleanType":"","cleanId":"","currentVacuumPowerMode":"fullPower","defaultVacuumPowerMode":"fullPower","globalPosition":[0,0],"batteryChargeLevel":90,"time":"2017-08-14T19:56:30Z"}
Thanks!

**Comment by peterchs** [comment]
Thanks for the feedback!  Had originally just dumped the logs for debugging but could print out the status updates and key changes without the json structure

**Comment by mczac** [comment]
Actually, this is really very minor, I might do it later. What happens when you have multiple Dyson devices the MQTT status update initiate log updates for other products like Fan.

**Comment by peterchs** [comment]
Not sure I follow.  If you have two devices there should be two separate
MQTT client objects which will subscribe/publish to each device on its own.


If you mean you want to watch the logs for different devices, should be
possible to include the device username or some other identifier at the
start of each log line.

Peter

**Comment by mczac** [comment]
Sorry, my bad, I noticed that homebridge-dyson-link started to write MQTT status into the log today. I never noticed it before. Thought that your module was pulling all Dyson products update. Apologies. closing in now. thank you.
